version: '2'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=bpleague
      - POSTGRES_PASSWORD=bpleague
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data

  bpleague-back:
    build: ./back/
    volumes:
      - ./volumes/logs:/logs
    environment:
      - VIRTUAL_HOST=api.bpleague.cs-campus.fr
      - LETSENCRYPT_HOST=api.bpleague.cs-campus.fr
      - LETSENCRYPT_EMAIL=alexistacnet@gmail.com

  bpleague-front:
    image: nginx:latest
    volumes:
      - ./front/dist:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=bpleague.cs-campus.fr
      - LETSENCRYPT_HOST=bpleague.cs-campus.fr
      - LETSENCRYPT_EMAIL=alexistacnet@gmail.com

  proxy:
    image: jwilder/nginx-proxy:latest
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    volumes:
      - /usr/share/nginx/html
      - ./front/certs:/etc/nginx/certs:ro
      - /etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 80:80
      - 443:443

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:latest
    volumes_from:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./front/certs:/etc/nginx/certs:rw